//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.29 at 02:10:09 PM EET 
//


package eg.gov.iti.jets.models.singleChat;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SingleChatMessage" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="serialVersionUID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element name="singleChatMessageId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="messageTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                   &lt;element name="font" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "singleChatMessage"
})
@XmlRootElement(name = "SingleChat")
public class SingleChat {

    @XmlElement(name = "SingleChatMessage")
    protected List<SingleChat.SingleChatMessage> singleChatMessage;

    /**
     * Gets the value of the singleChatMessage property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the singleChatMessage property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSingleChatMessage().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SingleChat.SingleChatMessage }
     *
     *
     */
    public List<SingleChat.SingleChatMessage> getSingleChatMessage() {
        if (singleChatMessage == null) {
            singleChatMessage = new ArrayList<SingleChat.SingleChatMessage>();
        }
        return this.singleChatMessage;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="serialVersionUID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element name="singleChatMessageId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="messageTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *         &lt;element name="font" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "serialVersionUID",
            "singleChatMessageId",
            "userId",
            "content",
            "messageTimestamp",
            "font",
            "color"
    })
    public static class SingleChatMessage {

        protected Long serialVersionUID;
        protected Integer singleChatMessageId;
        protected Integer userId;
        protected String content;
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar messageTimestamp;
        protected String font;
        protected String color;

        /**
         * Gets the value of the serialVersionUID property.
         *
         * @return possible object is
         * {@link Long }
         */
        public Long getSerialVersionUID() {
            return serialVersionUID;
        }

        /**
         * Sets the value of the serialVersionUID property.
         *
         * @param value
         *     allowed object is
         *     {@link Long }
         *
         */
        public void setSerialVersionUID(Long value) {
            this.serialVersionUID = value;
        }

        /**
         * Gets the value of the singleChatMessageId property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getSingleChatMessageId() {
            return singleChatMessageId;
        }

        /**
         * Sets the value of the singleChatMessageId property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setSingleChatMessageId(Integer value) {
            this.singleChatMessageId = value;
        }

        /**
         * Gets the value of the userId property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getUserId() {
            return userId;
        }

        /**
         * Sets the value of the userId property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setUserId(Integer value) {
            this.userId = value;
        }

        /**
         * Gets the value of the content property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * Gets the value of the messageTimestamp property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getMessageTimestamp() {
            return messageTimestamp;
        }

        /**
         * Sets the value of the messageTimestamp property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setMessageTimestamp(XMLGregorianCalendar value) {
            this.messageTimestamp = value;
        }

        /**
         * Gets the value of the font property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getFont() {
            return font;
        }

        /**
         * Sets the value of the font property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setFont(String value) {
            this.font = value;
        }

        /**
         * Gets the value of the color property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getColor() {
            return color;
        }

        /**
         * Sets the value of the color property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setColor(String value) {
            this.color = value;
        }

    }

}
